from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "questions.json"

LECTURES = {
    "01": ("임신 중 모성생리", "김병재"),
    "02": ("임신 전 상담/산전관리", "오경준"),
    "03": ("산전진단/산전태아평가", "김선민"),
    "04": ("정상분만의 관리/분만 중 태아 감시", "박찬욱"),
    "05": ("조산", "박지윤"),
    "06": ("산과 출혈", "박중신"),
    "07": ("임신 중 고혈압성 질환", "김병재"),
    "08": ("다태임신/발육부전/과숙아", "정영미"),
    "09": ("정상 산욕기/산욕기이상", "김현지"),
    "10": ("유산/자궁외임신", "조희영"),
}

WILLIAMS = {"label": "Williams Obstetrics 26e", "url": "https://accessmedicine.mhmedical.com/book.aspx?bookid=2977", "kind": "교과서"}
SOURCES = {
    "preconception": {"label": "ACOG: Prepregnancy Counseling", "url": "https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2019/01/prepregnancy-counseling", "kind": "현재 지침"},
    "progesterone": {"label": "ACOG: Updated Progestogen Guidance (updated 2025)", "url": "https://www.acog.org/clinical/clinical-guidance/practice-advisory/articles/2023/04/updated-guidance-use-of-progestogen-supplementation-for-prevention-of-recurrent-preterm-birth", "kind": "현재 지침"},
    "short_cervix": {"label": "SMFM Consult #70: Short Cervix", "url": "https://publications.smfm.org/publications/560-society-for-maternal-fetal-medicine-consult-series-70/", "kind": "현재 지침"},
    "fhr": {"label": "ACOG CPG #10: Intrapartum FHR Monitoring (2025)", "url": "https://www.acog.org/clinical/clinical-guidance/clinical-practice-guideline/articles/2025/10/intrapartum-fetal-heart-rate-monitoring-interpretation-and-management", "kind": "현재 지침"},
    "pprom": {"label": "ACOG PB #217: Prelabor Rupture of Membranes", "url": "https://www.acog.org/clinical/clinical-guidance/practice-bulletin/articles/2020/03/prelabor-rupture-of-membranes", "kind": "현재 지침"},
    "fgr": {"label": "SMFM Consult #52: Fetal Growth Restriction", "url": "https://publications.smfm.org/publications/289-society-for-maternal-fetal-medicine-consult-series-52/", "kind": "현재 지침"},
    "ttts": {"label": "SMFM Consult #72: TTTS/TAPS", "url": "https://publications.smfm.org/publications/574-society-for-maternal-fetal-medicine-consult-series-72/", "kind": "현재 지침"},
    "preeclampsia": {"label": "ACOG PB #222: Gestational Hypertension and Preeclampsia", "url": "https://www.acog.org/clinical/clinical-guidance/practice-bulletin/articles/2020/06/gestational-hypertension-and-preeclampsia", "kind": "현재 지침"},
    "chap": {"label": "ACOG: CHAP Study Integration", "url": "https://www.acog.org/clinical/clinical-guidance/practice-advisory/articles/2022/04/clinical-guidance-for-the-integration-of-the-findings-of-the-chronic-hypertension-and-pregnancy-chap-study", "kind": "현재 지침"},
    "pph": {"label": "ACOG PB #183: Postpartum Hemorrhage", "url": "https://www.acog.org/clinical/clinical-guidance/practice-bulletin/articles/2017/10/postpartum-hemorrhage", "kind": "현재 지침"},
    "pas": {"label": "ACOG/SMFM: Placenta Accreta Spectrum", "url": "https://www.acog.org/clinical/clinical-guidance/obstetric-care-consensus/articles/2018/12/placenta-accreta-spectrum", "kind": "현재 지침"},
    "postpartum_bc": {"label": "ACOG: Postpartum Birth Control", "url": "https://www.acog.org/womens-health/faqs/postpartum-birth-control", "kind": "현재 지침"},
    "breastfeeding": {"label": "ACOG: Breastfeeding Challenges", "url": "https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2021/02/breastfeeding-challenges", "kind": "현재 지침"},
    "epl": {"label": "ACOG PB #200: Early Pregnancy Loss", "url": "https://www.acog.org/clinical/clinical-guidance/practice-bulletin/articles/2018/11/early-pregnancy-loss", "kind": "현재 지침"},
    "ectopic": {"label": "ACOG: Ectopic Pregnancy", "url": "https://www.acog.org/womens-health/faqs/ectopic-pregnancy", "kind": "현재 지침"},
}


def predicted(lecture: str, sequence: int, *, stem: str, choices: list[str], answers: list[int], concept: str,
              key: str, steps: list[str], choice_explanations: list[str], criteria: list[str], review: str,
              source_keys: list[str]) -> dict:
    title, professor = LECTURES[lecture]
    number = 950 + sequence
    return {
        "lectureNumber": lecture,
        "lectureTitle": title,
        "sourceLectureTitle": title,
        "year": "2026",
        "number": number,
        "displayNumber": f"2026 예상 {sequence}",
        "sourceKind": "2026-predicted",
        "examStatus": "2026 강의 강조점 기반 예상문제 · 비출제",
        "answers": answers,
        "answerStatus": "강의록·교과서·현재 지침 대조 예상정답",
        "answerRaw": ",".join(map(str, answers)),
        "answerNote": "실제 출제 문제가 아닌 고난도 학습용 예상문제",
        "professor2026": professor,
        "professorAtExam": professor,
        "importance": "predicted-high",
        "classificationStatus": "2026 강의록 주제 기준",
        "yearStatus": "2026 예상문제",
        "id": f"gendev2-{lecture}-2026-q{number}",
        "stem": stem,
        "choices": choices,
        "content": [{"type": "text", "text": stem}],
        "choiceStatus": "자체 작성 5지선다",
        "assets": [],
        "sourcePages": [],
        "keyConcepts": [title, concept],
        "explanation": {
            "conceptGroup": concept,
            "keyJudgment": key,
            "reasoningSteps": steps,
            "choiceExplanations": choice_explanations,
            "diagnosticCriteria": criteria,
            "conceptReview": review,
            "evidenceStatus": "2026 강의 필기·Williams 26e·현재 공식 지침 대조 · 2026-08-05",
            "sources": [WILLIAMS, *[SOURCES[item] for item in source_keys]],
        },
        "explanationReviewStatus": "2026 강의 필기·Williams 26e·현재 공식 지침 대조 · 2026-08-05",
    }


PREDICTED = [
    predicted("01", 1,
        stem="임신 28주인 건강한 초임부의 동맥혈가스가 pH 7.44, PaCO₂ 29 mmHg, HCO₃⁻ 20 mEq/L이다. 호흡곤란은 없고 산소포화도는 99%이다. 가장 알맞은 해석은?",
        choices=["대사산증", "급성 호흡알칼리증", "임신의 정상적인 만성 호흡알칼리증", "보상된 호흡산증", "혼합성 대사알칼리증"], answers=[3],
        concept="임신의 호흡생리", key="프로게스테론이 환기량을 늘려 PaCO₂가 약 30 mmHg로 낮아지고 신장이 중탄산을 배설한다. 정상 임신의 보상된 만성 호흡알칼리증이다.",
        steps=["산소포화도와 증상이 정상이라 급성 폐질환 단서가 없다.", "PaCO₂ 감소가 1차 변화이고 HCO₃⁻도 함께 낮아 만성 신장 보상이 보인다.", "임신 중 tidal volume과 minute ventilation 증가에 의한 정상 적응으로 판정한다."],
        choice_explanations=["대사산증이면 HCO₃⁻ 감소가 1차이며 pH가 낮아지는 방향이어야 한다.", "급성 호흡알칼리증에서는 신장 보상 시간이 부족해 HCO₃⁻ 감소가 이 정도로 동반되지 않는다.", "정답. 임신의 과환기와 신장성 중탄산 배설이 함께 나타난 전형적 조합이다.", "호흡산증은 PaCO₂가 상승해야 하므로 반대이다.", "대사알칼리증은 HCO₃⁻ 상승이 핵심이며 이 검사와 맞지 않는다."],
        criteria=["정상 임신: PaCO₂ 약 28–32 mmHg, HCO₃⁻ 약 18–22 mEq/L의 보상된 호흡알칼리증", "새 저산소혈증·흉통·빈호흡이 있으면 정상 적응으로 치부하지 말고 폐색전증 등 평가"],
        review="횡격막은 올라가지만 tidal volume은 증가한다. 기능적잔기용량은 감소하고 분당환기량은 증가하며, 모체 PaCO₂ 저하는 태아에서 모체로 CO₂ 이동을 돕는다.", source_keys=[]),
    predicted("01", 2,
        stem="임신 30주인 초임부가 피로를 호소한다. 혈색소 10.6 g/dL, 평균적혈구용적 88 fL, 혈청 ferritin 42 ng/mL이다. 출혈은 없다. 가장 알맞은 설명은?",
        choices=["철결핍빈혈이 확진된다", "임신의 혈장량 증가에 따른 생리적 혈액희석 가능성이 크다", "용혈성빈혈이 가장 의심된다", "엽산결핍으로 인한 거대적혈구빈혈이다", "임신 중 혈장량은 적혈구량보다 적게 증가한다"], answers=[2],
        concept="생리적 빈혈과 철결핍 감별", key="정상 MCV와 보존된 ferritin, 경계성 혈색소는 혈장량이 적혈구량보다 더 크게 증가하는 임신의 생리적 혈액희석을 지지한다.",
        steps=["빈혈의 정도뿐 아니라 MCV와 ferritin으로 철 저장을 확인한다.", "ferritin이 낮지 않고 정구성이므로 철결핍·엽산결핍 단서가 약하다.", "임신 중 혈장량 증가가 적혈구량 증가를 앞서는 생리적 변화로 해석한다."],
        choice_explanations=["철결핍은 보통 ferritin 감소가 먼저 나타나며 진행하면 소구성이 된다.", "정답. 혈장량이 약 40–50% 증가해 상대적 혈액희석이 생긴다.", "용혈이면 망상적혈구·LDH·간접빌리루빈 증가와 haptoglobin 감소 같은 근거가 필요하다.", "엽산결핍은 대개 거대적혈구성으로 MCV가 상승한다.", "임신에서는 혈장량이 적혈구량보다 더 크게 증가하므로 문장이 반대이다."],
        criteria=["임신 빈혈 선별 기준은 임신 시기와 사용하는 체계에 따라 다르므로 Hb만으로 원인을 확정하지 않는다", "철결핍은 ferritin 저하가 가장 유용한 저장철 단서이며 염증이 있으면 해석에 주의"],
        review="생리적 빈혈은 진단명이 아니라 혈액희석 현상이다. 실제 철결핍은 흔하므로 식이·보충력, ferritin, MCV와 필요시 추가 철검사를 함께 본다.", source_keys=[]),
    predicted("01", 3,
        stem="임신 26주인 초임부의 소변막대검사에서 포도당 2+가 확인되었다. 공복혈당은 82 mg/dL이고 증상은 없다. 다음 설명 중 옳은 것은?",
        choices=["요당만으로 임신성당뇨병을 진단한다", "임신 중 사구체여과율 감소가 요당의 원인이다", "신장 포도당 역치 저하로 정상 임신에서도 요당이 나타날 수 있다", "공복혈당은 정상 임신에서 보통 상승한다", "추가 혈당 선별검사는 필요하지 않다"], answers=[3],
        concept="임신의 탄수화물·신장 생리", key="임신에서는 GFR 증가와 포도당 재흡수 역치 변화로 요당이 생길 수 있어 요당 단독으로 당뇨를 진단하지 않는다.",
        steps=["요당과 혈당은 같은 검사가 아님을 구분한다.", "정상 공복혈당과 무증상이라는 점에서 즉시 당뇨 확진은 불가하다.", "정규 임신성당뇨 선별 일정에 따라 혈당 기반 검사를 시행한다."],
        choice_explanations=["요당은 민감도와 특이도가 부족해 진단검사가 아니다.", "정상 임신에서는 신혈류와 GFR이 증가한다.", "정답. 여과량 증가와 역치 변화 때문에 혈당이 정상이어도 요당이 가능하다.", "태아-태반 포도당 이용과 대사 변화로 공복혈당은 오히려 낮아지는 경향이 있다.", "요당은 진단은 아니지만 표준 시기의 혈당 기반 선별검사를 생략할 근거도 아니다."],
        criteria=["임신성당뇨 진단은 기관이 채택한 1단계 75-g 또는 2단계 50-g 선별→100-g 진단 전략의 혈당 기준 사용", "요당은 당뇨 확진 기준이 아님"],
        review="임신 후반에는 인슐린 저항이 증가해 식후혈당이 높고 오래 지속될 수 있지만 공복혈당은 낮아질 수 있다. 요당과 혈당을 분리해서 묻는 문제가 반복된다.", source_keys=[]),

    predicted("02", 1,
        stem="임신 전부터 제2형 당뇨병이 있었으나 3년간 치료하지 않은 36세 여자가 임신 7주 3일에 내원했다. HbA1c는 12.3%이다. 가장 적절한 상담과 처치는?",
        choices=["태아기형이 확정되었으므로 즉시 임신을 종결한다", "경구혈당강하제를 모두 중단하고 24주까지 기다린다", "즉시 혈당을 최적화하고 망막·신장 등 합병증을 평가하며 기형 선별 계획을 상담한다", "임신 초기에는 혈당 조절이 태아 예후에 영향을 주지 않는다", "엽산만 처방하면 추가 평가가 필요 없다"], answers=[3],
        concept="임신 전 당뇨와 배아기 위험", key="HbA1c 12.3%는 배아 기관형성기의 고혈당 노출을 뜻한다. 기형을 확정하지는 않지만 즉시 전문팀 혈당관리, 모체 합병증 평가와 정밀 산전검사 상담이 필요하다.",
        steps=["임신 7주는 심장·신경관 등 기관형성기임을 확인한다.", "매우 높은 HbA1c를 선천기형·유산 위험 증가 신호로 해석하되 확진과 위험을 구분한다.", "인슐린 중심의 개별 치료와 안저·신장·혈압 평가, 정확한 주수 확인과 표적 초음파 계획을 세운다."],
        choice_explanations=["위험 증가는 기형 확정이 아니므로 수치만으로 임신 종결을 결정하지 않는다.", "치료를 미루면 지속 고혈당으로 모체·태아 위험이 더 커진다.", "정답. 혈당과 동반 장기질환을 즉시 관리하고 위험을 수치가 아닌 상담 과정으로 설명한다.", "기관형성기는 고혈당의 기형 유발 위험이 가장 중요한 시기다.", "엽산은 필요하지만 중증 고혈당과 당뇨 합병증 평가를 대체하지 못한다."],
        criteria=["임신 전 당뇨: 임신 전에 진단된 1형 또는 2형 당뇨", "HbA1c는 최근 수개월의 노출을 반영하며 단일 수치가 태아기형을 확진하지 않음"],
        review="임신 전 상담의 목적은 위험을 숨기거나 임신 결과를 단정하는 것이 아니라 수정 가능한 위험을 줄이는 것이다. 혈당, 혈압, 신장·망막 상태와 약제를 임신 전에 최적화하는 것이 가장 효과적이다.", source_keys=["preconception"]),
    predicted("02", 2,
        stem="이전 임신 23주에 자연 조산한 여자가 단태임신 18주에 왔다. 증상은 없고 질초음파 자궁목길이는 29 mm이다. 현재 권고에 가장 맞는 처치는?",
        choices=["과거력만으로 17-OHPC를 시작한다", "과거력만으로 질 프로게스테론을 시작한다", "연속 질초음파 자궁목길이 감시를 하고 짧아질 때 중재를 결정한다", "예방적 자궁목원형묶음술을 모든 환자에게 시행한다", "절대안정과 예방적 항생제를 처방한다"], answers=[3],
        concept="재발성 조산 예방의 최신 변경점", key="이전 자연 조산력이 있지만 현재 자궁목 29 mm로 짧지 않다. 17-OHPC는 권하지 않고, 짧은 자궁목이 없는 상태에서 질 프로게스테론도 자동 투여하지 않으며 연속 자궁목 감시가 핵심이다.",
        steps=["이전 조산의 유형과 현재 단태임신 여부를 확인한다.", "질초음파 자궁목길이 29 mm는 ≤25 mm의 짧은 자궁목 기준에 들지 않는다.", "2025 ACOG 업데이트에 따라 과거력만으로 프로게스테론을 처방하지 않고 길이 변화에 맞춰 cerclage/프로게스테론을 논의한다."],
        choice_explanations=["17-OHPC는 효과 근거 부족과 허가 철회 이후 재발 예방에 권고되지 않는다.", "짧은 자궁목이 없으면 이전 자연 조산력만으로 질 프로게스테론을 제공하지 않는 것이 현재 ACOG 권고다.", "정답. 중기 연속 질초음파 감시로 치료가 필요한 짧은 자궁목을 찾는다.", "cerclage 적응증은 전형적 자궁목무력증 과거력, 짧은 자궁목과 과거 조산 등으로 선별한다.", "침상안정과 무증상 예방 항생제는 재발 조산을 줄이는 표준 전략이 아니다."],
        criteria=["짧은 자궁목: 중기 질초음파 길이 ≤25 mm", "이전 자연 조산 + 짧은 자궁목이면 환자별로 cerclage 등 중재 검토", "짧은 자궁목이 없으면 질 프로게스테론을 재발 예방 목적으로 자동 제공하지 않음"],
        review="강의의 오래된 프로게스테론 연구와 현재 권고를 구분해야 한다. 약 이름을 외우기보다 과거 조산 유형, 단태/다태, 현재 자궁목길이와 개대 여부를 순서대로 본다.", source_keys=["progesterone", "short_cervix"]),
    predicted("02", 3,
        stem="Marfan 증후군이 있는 31세 여자가 임신을 계획한다. 심초음파에서 대동맥근부 지름은 4.7 cm이다. 가장 적절한 임신 전 상담은?",
        choices=["임신과 무관한 소견이므로 바로 임신을 시도한다", "임신 중 CT만 반복하면 충분하다", "임신을 미루고 대동맥 전문 다학제 평가와 예방적 수술 필요성을 먼저 논의한다", "임신 20주가 되면 위험 평가를 시작한다", "베타차단제는 모든 경우 절대 금기이므로 중단한다"], answers=[3],
        concept="Marfan 증후군과 임신 전 대동맥 위험", key="대동맥근부 4.7 cm인 Marfan 환자는 임신 중 박리 위험이 높다. 임신 전에 대동맥팀과 위험을 평가하고 예방적 수술을 우선 논의해야 한다.",
        steps=["Marfan 자체보다 대동맥 침범의 크기와 성장 속도가 임신 위험을 결정함을 확인한다.", "4.7 cm는 임신 전에 수술을 권고하는 고위험 범위에 해당한다.", "유전상담, 영상, 약제와 임신 시 감시·분만 계획을 다학제로 세운다."],
        choice_explanations=["임신의 혈역학적 부담은 대동맥 확장·박리 위험을 높인다.", "임신 중 방사선 노출 검사만 반복하는 접근이 아니라 임신 전 위험 감소가 우선이다.", "정답. 임신을 시작하기 전에 수술 적응증과 잔여 위험을 논의한다.", "위험 사건은 임신 초기부터 가능하므로 20주까지 기다리지 않는다.", "일부 베타차단제는 위험-편익을 평가해 사용하며 임의 중단이 더 위험할 수 있다."],
        criteria=["Marfan에서 대동맥근부/상행대동맥 >4.5 cm이면 임신 전 예방적 수술 권고", "4.0–4.5 cm도 빠른 성장·가족력 등 추가 위험에 따라 수술 고려"],
        review="심장질환 상담은 ‘임신 가능/불가능’ 한 문장으로 끝나지 않는다. 대동맥 크기·성장, 가족력, 판막기능, 약제, 유전과 임신 중 영상·분만 장소까지 미리 계획한다.", source_keys=["preconception"]),

    predicted("03", 1,
        stem="임신 12주인 39세 미분만부의 cfDNA 선별검사에서 21번 삼염색체증 고위험이 확인되었다. 초음파는 정상이다. 다음 단계로 가장 적절한 것은?",
        choices=["정상 초음파이므로 결과를 무시한다", "cfDNA를 같은 검사실에서 반복한다", "유전상담 후 융모막융모생검 또는 이후 양수천자로 진단을 확인한다", "모체혈청 AFP만 검사한다", "선별검사 결과만으로 치료유산을 시행한다"], answers=[3],
        concept="양성 선별검사 뒤 확진", key="cfDNA는 민감도가 높은 선별검사이지 진단검사가 아니다. 정상 초음파와 무관하게 유전상담 후 CVS 또는 양수천자로 확인한다.",
        steps=["선별검사와 진단검사를 구분한다.", "임신 12주에는 CVS가 가능한 시기이고, 기다리면 양수천자도 선택할 수 있다.", "검사 특성·시술 위험·환자 가치에 따라 진단법을 공동 결정한다."],
        choice_explanations=["정상 초음파는 염색체 이상을 완전히 배제하지 못한다.", "단순 반복은 태반 모자이크나 생물학적 위양성을 해결하는 확진법이 아니다.", "정답. 태아/태반 유전물질을 직접 분석하는 진단검사가 필요하다.", "AFP는 주로 개방성 신경관결손 선별에 쓰며 21번 삼염색체증 확진검사가 아니다.", "선별 양성만으로 비가역적 결정을 내리지 않는다."],
        criteria=["cfDNA 양성: 유전상담 + 상세 초음파 + CVS/양수천자 진단검사 제안", "CVS와 양수천자의 선택은 주수·태반 모자이크 가능성·환자 선호에 따라 결정"],
        review="양성예측도는 유병률의 영향을 받는다. 고위험 결과도 위양성이 가능하고, 저위험 결과도 모든 유전질환을 배제하지는 않는다.", source_keys=[]),
    predicted("03", 2,
        stem="임신 36주인 태아성장제한 임신부의 생물리학적계수(BPP)가 NST 비반응 0점, 호흡 0점, 움직임 2점, 긴장도 0점, 양수 2점으로 총 4점이다. 반복검사에서도 동일하다. 가장 적절한 처치는?",
        choices=["1주 후 BPP 재검", "모체 혈청 AFP 검사", "분만을 계획한다", "융모막융모생검", "태동이 있으므로 추가 조치하지 않는다"], answers=[3],
        concept="BPP 해석과 분만 결정", key="반복 BPP 4/10은 비정상으로 태아 저산소혈증 위험을 시사한다. 36주 FGR에서는 지연보다 분만이 적절하다.",
        steps=["각 항목 점수를 합산해 4/10임을 확인한다.", "양수는 보존되었지만 NST·호흡·긴장도 이상이 동시에 있어 안심할 수 없다.", "주수 36주와 FGR을 함께 고려해 분만을 결정한다."],
        choice_explanations=["4/10을 일주일 방치하면 저산소 위험을 놓칠 수 있다.", "AFP는 현재 태아 산소상태 평가와 무관하다.", "정답. 비정상 검사가 지속되는 36주 태아는 분만 쪽의 위험-편익이 유리하다.", "CVS는 임신 1삼분기 유전 진단 시술이며 현재 적응이 아니다.", "일부 태동만으로 다른 BPP 이상을 상쇄할 수 없다."],
        criteria=["BPP 8–10점: 대체로 정상(단, 양수과소는 별도 평가)", "6점: 애매하여 주수·임상상에 따라 반복/분만", "4점 이하: 비정상으로 대개 추가 즉시 평가와 분만 고려"],
        review="BPP는 급성 표지(NST·호흡·움직임·긴장도)와 비교적 만성 표지인 양수량을 합친다. 총점뿐 아니라 양수과소와 임신 주수를 따로 본다.", source_keys=["fgr"]),
    predicted("03", 3,
        stem="임신 31주인 초임부의 태아 예상체중은 2백분위수이고 탯줄동맥 도플러에서 이완기말 혈류 역전(REDV)이 반복 확인된다. 처치는?",
        choices=["외래에서 2주 후 도플러 재검", "입원·스테로이드·집중감시 후 30–32주 분만을 준비한다", "38–39주까지 기다린다", "실데나필을 시작한다", "침상안정만 시행한다"], answers=[2],
        concept="중증 FGR과 REDV", key="REDV는 중증 태반저항과 높은 사산 위험을 뜻한다. 입원, 스테로이드, 빈번한 CTG와 31주 분만 준비가 필요하며 32주 미만이면 MgSO₄ 신경보호도 고려한다.",
        steps=["EFW <3백분위수로 severe FGR을 확인한다.", "REDV를 정상·저항증가·AEDV보다 더 악화된 도플러 단계로 분류한다.", "31주는 SMFM 권고 분만 창 30–32주에 들어가므로 감시만 장기 지속하지 않는다."],
        choice_explanations=["REDV를 외래 2주 간격으로 보는 것은 감시 강도가 부족하다.", "정답. 입원과 태아 폐성숙·신경보호를 준비하면서 신속히 분만한다.", "정상 도플러 3–10백분위 FGR에서 고려하는 시기이지 REDV에는 위험하다.", "실데나필은 FGR 치료로 권고되지 않는다.", "활동 제한만으로 태반 혈류를 정상화하거나 사산을 예방한다는 근거가 없다."],
        criteria=["FGR: EFW 또는 AC <10백분위수", "Severe FGR: EFW <3백분위수", "REDV: 입원·스테로이드·CTG 1–2회/일 이상, 30–32주 분만 권고"],
        review="FGR 분만시기는 체중 백분위만이 아니라 제대동맥 이완기 혈류로 단계화한다. 정상 38–39주, 감소/중증 37주, AEDV 33–34주, REDV 30–32주가 핵심 축이다.", source_keys=["fgr"]),

    predicted("04", 1,
        stem="옥시토신으로 유도분만 중인 임신 40주 초임부에게 10분간 자궁수축 6회와 반복 후기감속이 나타났다. 변이도는 중등도이고 산모 산소포화도는 99%이다. 우선 처치를 모두 고르면?",
        choices=["옥시토신 중단", "좌측위 변경", "정맥 수액과 저혈압 교정", "산모에게 10 L/min 산소를 일률적으로 투여", "옥시토신 용량 증가"], answers=[1,2,3],
        concept="빈수축을 동반한 Category II 소생술", key="tachysystole와 후기감속에서는 자궁자극을 줄이고 모체 체위·관류를 교정한다. 산모가 정상 산소화라면 산소를 관행적으로 주지 않는다.",
        steps=["10분에 5회를 초과하므로 tachysystole를 확인한다.", "원인인 옥시토신을 중단하고 좌측위·수액으로 자궁태반관류를 개선한다.", "변이도가 보존된 Category II를 재평가하되 악화·지속 시 신속 분만을 준비한다."],
        choice_explanations=["정답. 외인성 자궁자극을 즉시 제거한다.", "정답. 대정맥 압박을 줄여 모체 심박출량과 자궁태반관류를 개선한다.", "정답. 특히 경막외마취·저혈압이 있으면 수액과 원인 교정이 중요하다.", "정상 산소포화도에서 일률적 산소는 제대혈 pH·신생아 예후 개선이 확인되지 않아 권하지 않는다.", "수축 과다와 후기감속을 악화시키므로 반대 처치다."],
        criteria=["Tachysystole: 30분 평균으로 10분에 자궁수축 >5회", "Category II: Category I·III에 들지 않는 이질적 군; 변이도/가속과 감속의 깊이·지속을 함께 평가"],
        review="Category 이름만 보고 같은 처치를 하는 것이 아니라 원인을 고친다. oxytocin, 저혈압, 체위, 발열·산소화, 제대압박을 확인하고 재평가한다.", source_keys=["fhr"]),
    predicted("04", 2,
        stem="분만 중 태아심박동이 기저선 95회/분이고 변이도가 소실되었으며 반복 가변감속이 지속된다. 초기 자궁내 소생술에도 회복되지 않는다. 분류와 처치는?",
        choices=["Category I, 일상 감시", "Category II, 24시간 관찰", "Category III, 신속한 분만", "반응성 NST, 퇴원", "정상 조기감속, 옥시토신 증량"], answers=[3],
        concept="Category III 태아심박동", key="변이도 소실과 반복 가변감속/서맥의 조합은 Category III이다. 초기 교정에 반응하지 않으면 태아 산혈증 위험 때문에 신속히 분만한다.",
        steps=["기저선 서맥과 변이도 소실을 확인한다.", "반복 가변감속이 함께 있어 Category III 정의에 부합한다.", "가역 원인을 즉시 교정하고도 지속되면 분만 경로를 임상상에 맞춰 신속 결정한다."],
        choice_explanations=["Category I은 110–160, 중등도 변이도, 후기·가변감속 없음이 필요하다.", "이 추적은 단순 Category II가 아니며 장시간 관찰할 수 없다.", "정답. 소생술 불응 Category III는 expedited delivery 대상이다.", "NST 용어는 산전검사이며 현재 분만 중 비정상 추적이다.", "변이도 소실·서맥·가변감속은 정상 조기감속이 아니며 옥시토신 증량은 악화시킬 수 있다."],
        criteria=["Category III: 변이도 소실 + 반복 후기감속/반복 가변감속/서맥 중 하나, 또는 sinusoidal pattern", "초기 교정 불응 시 신속 분만"],
        review="중등도 변이도나 가속은 현재 산혈증 가능성이 낮다는 보호 단서다. 반대로 변이도 소실이 감속·서맥과 결합하면 위험도가 급격히 높아진다.", source_keys=["fhr"]),
    predicted("04", 3,
        stem="임신 39주 초임부가 자궁목 6 cm에서 양막파수 후 옥시토신을 투여받고 있다. 자궁내압카테터로 230 MVU가 4시간 유지되었으나 자궁목 변화가 없다. 태아상태는 안정적이다. 진단은?",
        choices=["잠복기 지연", "활성기 정지", "급속분만", "제2기 분만 정지", "자궁목무력증"], answers=[2],
        concept="활성기 정지 진단", key="활성기는 6 cm부터로 보고, 양막파수 상태에서 충분한 수축(≥200 MVU)이 4시간 지속되어도 개대가 없으면 활성기 정지 기준을 충족한다.",
        steps=["자궁목 6 cm이므로 잠복기가 아니라 활성기다.", "양막이 파수되었고 230 MVU로 수축이 충분함을 확인한다.", "4시간 무변화이므로 active-phase arrest로 진단한다."],
        choice_explanations=["6 cm 이후이므로 잠복기 진단을 적용하지 않는다.", "정답. 6 cm 이상·양막파수·충분한 수축 4시간 무진행 조건이 모두 충족된다.", "급속분만은 빠른 개대·분만이며 여기서는 진행이 없다.", "제2기는 완전개대 10 cm 이후이므로 아직 아니다.", "자궁목무력증은 주로 임신 중기 무통성 개대·유산의 문제다."],
        criteria=["활성기 시작: 자궁목 6 cm", "활성기 정지: ≥6 cm + 양막파수 + 4시간 충분한 수축 또는 6시간 불충분한 수축에도 개대 변화 없음", "충분한 자궁수축의 실용적 기준: 약 ≥200 MVU"],
        review="너무 이른 제왕절개를 피하려면 6 cm 이전에는 active-phase arrest를 진단하지 않는다. 수축이 불충분하면 옥시토신으로 충분한 시간을 확보한 뒤 판정한다.", source_keys=["fhr"]),

    predicted("05", 1,
        stem="임신 32주 초임부가 2시간 전부터 물 같은 질분비물을 호소한다. 나이트라진과 ferning이 양성이고 발열·자궁압통·태아곤란은 없다. 가장 적절한 처치는?",
        choices=["즉시 옥시토신 유도분만", "기대요법, antenatal steroid와 latency antibiotics", "자궁목원형묶음술", "양수주입 후 퇴원", "장기 유지 목적의 반복 자궁수축억제제만 투여"], answers=[2],
        concept="32주 PPROM 관리", key="감염·태반조기박리·태아곤란이 없는 32주 PPROM은 입원 기대요법, 스테로이드와 latency antibiotics가 기본이다. 분만 임박 가능성이 크면 32주 미만 MgSO₄도 고려한다.",
        steps=["막파수 검사를 통해 PPROM을 확인한다.", "즉시 분만 적응증인 감염·태아곤란·활동성 진통·조기박리를 찾는다.", "해당 소견이 없고 34주 미만이므로 감시하며 폐성숙과 임신 연장을 위한 처치를 한다."],
        choice_explanations=["안정된 32주 PPROM을 모두 즉시 유도하지는 않는다.", "정답. 감염 감시와 함께 스테로이드·잠복기 항생제로 신생아 이득을 높인다.", "막이 이미 파열된 상태에서 예방적 cerclage는 감염·손상 위험이 있어 적응이 아니다.", "양수주입은 만성적으로 막을 복구하지 못하며 퇴원 감시는 부적절하다.", "tocolysis는 특정 상황에서 스테로이드 시간을 벌기 위한 제한적 판단이지 단독 장기치료가 아니다."],
        criteria=["PPROM: 진통 시작 전, 37주 미만의 양막파수", "즉시 분만 고려: 임상적 감염, 태아상태 악화, 태반조기박리, 진행 진통 등", "24–33+6주 안정 PPROM: 기대요법 + 스테로이드 + latency antibiotics"],
        review="PPROM 문제는 먼저 주수, 다음 감염·태아곤란·진통 여부를 본다. 항생제는 GBS 예방만이 아니라 잠복기 연장 요법을 구분하고, MgSO₄는 분만이 임박한 32주 미만 신경보호 목적이다.", source_keys=["pprom"]),
    predicted("05", 2,
        stem="과거 조산력이 없는 단태임신 초임부가 임신 21주에 시행한 질초음파에서 자궁목길이 18 mm이다. 개대는 없고 증상도 없다. 가장 적절한 처치는?",
        choices=["질 프로게스테론", "17-OHPC 근육주사", "자궁목원형묶음술", "자궁목페서리", "예방적 항생제"], answers=[1],
        concept="무증상 짧은 자궁목", key="과거 조산력이 없는 단태임신에서 24주 전 질초음파 자궁목길이 ≤20 mm이면 질 프로게스테론을 권고한다.",
        steps=["측정법이 질초음파인지 확인한다.", "18 mm는 ≤20 mm로 치료 권고 범위다.", "과거 조산·개대가 없으므로 cerclage가 아니라 질 프로게스테론을 선택한다."],
        choice_explanations=["정답. 무증상 단태임신의 짧은 자궁목에서 조산 위험을 줄인다.", "17-OHPC는 짧은 자궁목 치료로 권고되지 않는다.", "과거 조산 없이 10–25 mm이고 개대가 없으면 cerclage를 권하지 않는다.", "페서리는 이 상황의 표준 권고가 아니다.", "감염 근거가 없는 무증상 짧은 자궁목에 예방 항생제는 효과가 없다."],
        criteria=["과거 조산 없는 단태임신의 짧은 자궁목: 질초음파 ≤25 mm", "≤20 mm, 24주 전: 질 프로게스테론 권고", "21–25 mm: 공동의사결정으로 고려"],
        review="자궁목길이는 복부초음파가 아니라 표준화된 질초음파로 판정한다. 과거 조산력과 실제 개대 여부가 프로게스테론·cerclage 선택을 바꾼다.", source_keys=["short_cervix"]),
    predicted("05", 3,
        stem="현재 임신 13주인 여자가 이전 임신 19주에 진통 없이 자궁목이 열리고 양막이 돌출되어 유산했다. 감염·태반조기박리 증거는 없었다. 재발 예방으로 가장 적절한 것은?",
        choices=["경과관찰만 한다", "history-indicated cerclage", "임신 28주부터 항생제", "증상 발생 뒤 스테로이드만 투여", "예방적 옥시토신"], answers=[2],
        concept="병력 적응 자궁목원형묶음술", key="임신 중기 무통성 자궁목 개대와 유산은 전형적 자궁목무력증 병력이다. 임신 초기 말에 history-indicated cerclage가 적절하다.",
        steps=["이전 손실이 진통·막파수보다 무통성 개대로 시작했는지 확인한다.", "현재 13주로 예방적 봉합을 시행할 적절한 시기임을 본다.", "감염·출혈·진통 같은 금기가 없는지 확인하고 cerclage를 계획한다."],
        choice_explanations=["전형적 재발 고위험 병력을 관찰만 하면 예방 기회를 놓친다.", "정답. 병력 적응 cerclage로 임신 중기 무통성 개대 재발을 예방한다.", "항생제는 자궁목의 구조적 기능부전을 교정하지 않는다.", "스테로이드는 조산이 임박했을 때 태아 성숙을 돕지만 원인 예방은 아니다.", "옥시토신은 자궁수축을 유발하므로 예방과 반대다."],
        criteria=["자궁목무력증: 통증·규칙 수축 없이 임신 중기 자궁목 개대가 진행해 임신손실/극조산", "History-indicated cerclage는 전형적 과거력이 있을 때 보통 12–14주 무렵 고려"],
        review="‘19주 유산’이라는 주수만으로 진단하지 말고 시작 양상을 본다. 통증 없는 개대·양막돌출이면 자궁목무력증, 수축·감염·막파수가 먼저면 다른 재발 예방 전략이 필요하다.", source_keys=["short_cervix"]),

    predicted("06", 1,
        stem="임신 34주, 이전 제왕절개 2회의 병력이 있는 임신부가 통증 없는 선홍색 질출혈로 왔다. 활력징후와 태아심박동은 안정적이고 초음파에서 태반이 내자궁구를 덮는다. 우선 피해야 할 것은?",
        choices=["정맥로와 혈액검사 확보", "질경검사", "질초음파로 태반 위치 확인", "손가락 내진", "태아심박동 감시"], answers=[4],
        concept="전치태반의 초기 평가", key="통증 없는 후기 임신 출혈과 내자궁구를 덮는 태반은 전치태반이다. 태반을 손가락으로 건드리면 대량출혈을 유발할 수 있어 위치 확인 전후 모두 digital examination을 피한다.",
        steps=["통증 없는 선홍색 출혈을 태반조기박리의 통증·긴장항진과 구별한다.", "초음파로 전치태반을 확인하고 모체·태아 안정성을 동시에 평가한다.", "질경은 출혈 원인 확인에 조심스럽게 사용할 수 있지만 손가락 내진은 금기다."],
        choice_explanations=["출혈 재발에 대비한 정맥로·CBC·혈액형/교차시험은 필요하다.", "질경은 직접 태반을 촉지하지 않으며 다른 질병변·활동성 출혈 확인에 제한적으로 가능하다.", "질초음파는 전치태반에서도 안전하고 위치 확인에 정확하다.", "정답. 태반을 박리시켜 치명적 출혈을 일으킬 수 있다.", "태아상태 악화를 놓치지 않기 위해 감시한다."],
        criteria=["전치태반: 태반이 내자궁구를 덮음", "Low-lying placenta: 태반 가장자리가 내자궁구에 가깝지만 덮지 않음", "전형적 증상: 임신 후반 무통성 질출혈; 확진은 초음파"],
        review="전치태반은 출혈이 멎었어도 재출혈할 수 있다. 안정 여부·주수·출혈 반복을 보고 입원과 분만시기를 정하며, 모든 전치태반을 응급 제왕절개하는 것은 아니다.", source_keys=["pas"]),
    predicted("06", 2,
        stem="임신 32주 자간전증 임신부에게 갑작스러운 복통, 질출혈, 지속적 자궁압통과 긴장항진이 생겼다. 태아심박동은 80회/분으로 지속된다. 가장 적절한 처치는?",
        choices=["자궁수축억제 후 관찰", "양수천자", "응급 제왕절개분만과 모체 소생", "자궁동맥색전술만 시행", "34주까지 기다린다"], answers=[3],
        concept="태반조기박리와 태아곤란", key="통증·출혈·긴장항진과 지속 태아서맥은 태반조기박리에 의한 급성 태아저산소증을 시사한다. 생존 태아의 심각한 곤란에서는 모체 소생과 동시에 응급 제왕절개가 필요하다.",
        steps=["전치태반과 달리 통증과 자궁 긴장항진이 있다는 점을 잡는다.", "지속 서맥으로 즉각적인 태아위험을 확인한다.", "정맥로·혈액제제·응고검사를 준비하며 가장 빠른 안전한 분만을 시행한다."],
        choice_explanations=["조기박리에서 tocolysis는 출혈·태아저산소를 지연시킬 수 있다.", "진단은 임상적이며 양수천자가 분만을 늦춰서는 안 된다.", "정답. 태아곤란이 지속되는 생존 태아는 신속 분만이 필요하다.", "색전술은 특정 산후출혈 조절 수단이지 태아곤란을 해결하지 못한다.", "안정적 기대요법 대상이 아니며 34주라는 숫자보다 현재 위험이 우선이다."],
        criteria=["태반조기박리: 태반 분만 전 정상 부착 태반의 일부/전체 분리; 임상진단", "단서: 통증성 출혈, 자궁압통·긴장항진, 빈수축, 비안심 태아심박동", "초음파 음성이 조기박리를 배제하지 않음"],
        review="겉으로 보이는 출혈량은 태반 뒤 은폐출혈을 반영하지 못한다. 모체 쇼크, fibrinogen·혈소판·PT/aPTT와 태아상태를 함께 보며 수혈을 준비한다.", source_keys=["pph"]),
    predicted("06", 3,
        stem="질식분만 직후 1,200 mL 출혈, 혈압 85/55 mmHg, 맥박 128회/분이다. 태반은 완전하고 자궁저부가 크고 물렁하다. 천식 병력이 있다. 초기 처치로 옳지 않은 것은?",
        choices=["자궁마사지와 두 손 압박", "옥시토신", "정맥로 2개·혈액제제 준비", "carboprost", "출혈 시작 3시간 이내 tranexamic acid 고려"], answers=[4],
        concept="자궁무력 산후출혈", key="물렁한 자궁은 tone 문제인 자궁무력이다. 마사지·옥시토신·소생과 조기 TXA를 시행하되 carboprost는 기관지수축 때문에 천식에서 피한다.",
        steps=["출혈량 ≥1,000 mL와 쇼크로 산후출혈을 즉시 진단한다.", "4T 중 soft boggy uterus가 Tone임을 확인한다.", "원인치료와 대량출혈 소생을 동시에 시작하고 약물 금기를 확인한다."],
        choice_explanations=["자궁무력의 즉각적인 기계적 처치다.", "일차 자궁수축제로 적절하다.", "쇼크에서는 굵은 정맥로·검사·균형 수혈 준비를 지체하지 않는다.", "정답. PGF2α 유사체인 carboprost는 기관지수축을 일으켜 천식에서 금기/강한 주의다.", "지속 출혈에서 조기 TXA는 사망 위험을 줄이며 3시간 이내 투여가 중요하다."],
        criteria=["산후출혈: 출산 과정 24시간 이내 누적 실혈 ≥1,000 mL 또는 실혈량과 무관한 저혈량 징후", "원인 4T: Tone, Trauma, Tissue, Thrombin", "Atony 단서: 커지고 물렁한 자궁"],
        review="약제 선택은 동반질환을 묻기 좋다. methylergonovine은 고혈압, carboprost는 천식에서 피하고, misoprostol·옥시토신과 풍선·수술을 출혈 반응에 따라 단계적으로 사용한다.", source_keys=["pph"]),

    predicted("07", 1,
        stem="임신 30주 초임부의 혈압이 148/94 mmHg로 두 차례 확인되었다. 소변 단백은 음성이지만 혈소판 92,000/mm³이고 AST는 정상 상한의 2.4배이다. 진단은?",
        choices=["임신성고혈압", "중증 소견 없는 자간전증", "중증 소견을 동반한 자간전증", "만성고혈압", "HELLP는 아니므로 정상임신"], answers=[3],
        concept="단백뇨 없는 중증 자간전증", key="20주 이후 새 고혈압에 혈소판 <100,000과 간효소 2배 이상이 동반되면 단백뇨가 없어도 자간전증이며 중증 소견이 있다.",
        steps=["20주 이후 새 고혈압을 확인한다.", "단백뇨 음성에서 진단을 멈추지 않고 말단장기 소견을 본다.", "혈소판과 AST가 각각 중증 기준을 넘어 severe features로 분류한다."],
        choice_explanations=["임신성고혈압은 단백뇨·말단장기 기능장애가 없어야 한다.", "혈소판과 간효소가 중증 경계값을 넘었다.", "정답. 단백뇨 없이도 두 가지 severe feature가 성립한다.", "20주 이전부터 있거나 산후 지속된 고혈압 근거가 없다.", "HELLP 완전형 여부와 별개로 자간전증 중증 소견을 치료해야 한다."],
        criteria=["고혈압: ≥140/90 mmHg, 보통 4시간 간격 2회", "중증 혈압: ≥160/110 mmHg", "중증 소견: 혈소판 <100,000; Cr >1.1 mg/dL 또는 2배; AST/ALT ≥2배; 폐부종; 지속 신경증상 등"],
        review="자간전증은 ‘고혈압+단백뇨’만의 병이 아니다. 단백뇨가 없어도 혈소판·간·신장·폐·뇌 기능장애가 있으면 진단한다.", source_keys=["preeclampsia"]),
    predicted("07", 2,
        stem="임신 전부터 고혈압이 있던 여자가 임신 16주에 평균 혈압 146/92 mmHg이다. 장기기능은 정상이고 약을 중단한 상태다. 현재 권고에 가장 맞는 처치는?",
        choices=["160/110 mmHg가 될 때까지 치료하지 않는다", "labetalol 또는 nifedipine 등으로 치료를 시작/재개하고 저용량 aspirin 적응을 평가한다", "ACE 억제제를 재개한다", "이뇨제를 모든 환자에게 일차로 투여한다", "즉시 분만한다"], answers=[2],
        concept="CHAP 이후 만성고혈압 치료", key="CHAP 이후 ACOG는 임신 중 만성고혈압 치료 시작/조정 문턱을 140/90 mmHg로 낮췄다. 임신에 적합한 약과 자간전증 예방 aspirin을 검토한다.",
        steps=["20주 전부터 존재해 만성고혈압임을 확인한다.", "146/92가 현재 치료 문턱 140/90을 넘는지 본다.", "태아독성이 있는 RAAS 차단제를 피하고 임신 적합 약제를 선택한다."],
        choice_explanations=["160/110은 급성 중증 치료 경계이지 만성고혈압의 유일한 시작점이 아니다.", "정답. labetalol·서방 nifedipine 등이 흔한 1차 선택이며 고위험군 aspirin을 검토한다.", "ACE 억제제/ARB는 태아 신장독성 때문에 임신 중 피한다.", "이뇨제는 혈장량 문제와 적응증을 따져야 하며 모든 환자의 일차약이 아니다.", "안정된 16주 만성고혈압 자체는 분만 적응이 아니다."],
        criteria=["만성고혈압: 임신 전 또는 20주 이전 고혈압, 또는 산후 지속", "치료 시작/조정 기준: 140/90 mmHg", "급성 중증 고혈압 ≥160/110은 신속 치료"],
        review="시험의 오래된 ‘중증일 때만 항고혈압제’ 문구는 현재 만성고혈압 지침과 다를 수 있다. 진단 경계, 유지치료 문턱, 급성 중증치료 문턱을 분리한다.", source_keys=["chap", "preeclampsia"]),
    predicted("07", 3,
        stem="분만 24시간 뒤 혈압 172/112 mmHg인 산모가 전신 강직간대발작을 했다. 이전 간질력은 없다. 가장 우선적인 처치 조합은?",
        choices=["phenytoin 단독 후 퇴원", "magnesium sulfate, 기도 보호와 중증고혈압 치료", "이뇨제만 투여", "발작이 끝났으므로 관찰", "뇌 MRI 결과가 나올 때까지 치료 보류"], answers=[2],
        concept="산후 자간증", key="산후 24시간의 새 발작과 중증고혈압은 우선 자간증으로 다룬다. 기도·외상 보호, MgSO₄와 신속 혈압치료를 먼저 하고 다른 신경학적 원인을 병행 평가한다.",
        steps=["산후에도 자간증이 발생할 수 있음을 인식한다.", "발작 재발과 뇌출혈 위험을 각각 MgSO₄와 항고혈압제로 줄인다.", "국소결손·48시간 이후 발작·지속 혼수 등 비전형이면 뇌영상과 대체진단 평가를 강화한다."],
        choice_explanations=["MgSO₄가 자간증 재발 예방에서 phenytoin보다 우월하다.", "정답. ABC 안정화, MgSO₄, 중증고혈압 치료가 동시에 필요하다.", "폐부종 같은 적응이 없으면 이뇨제 단독은 핵심 치료가 아니다.", "한 번의 발작도 재발·흡인·뇌혈관 합병증 위험이 있다.", "검사는 치료와 병행하며 MgSO₄를 영상까지 미루지 않는다."],
        criteria=["자간증: 자간전증 환자에서 다른 원인으로 설명되지 않는 새 강직간대·국소·다초점 발작", "산후에도 발생 가능; >48시간, 국소신경결손, 지속 혼수 등은 대체진단 적극 평가"],
        review="MgSO₄는 항고혈압제가 아니므로 severe BP는 labetalol·hydralazine·즉방 nifedipine 등으로 별도 신속 치료한다. 독성은 반사·호흡·소변량을 감시하고 calcium으로 역전한다.", source_keys=["preeclampsia"]),

    predicted("08", 1,
        stem="임신 23주 MCDA 쌍태임신에서 한 태아의 최대수직양수포켓은 10 cm, 다른 태아는 1 cm이다. 작은 태아의 방광이 보이지 않고 제대동맥 이완기말 혈류가 역전되어 있다. 진단과 치료는?",
        choices=["TTTS stage I—2주 후 관찰", "TTTS stage II—양수감압만", "TTTS stage III—태아경 레이저 응고", "TAPS—즉시 제왕절개", "선택적 FGR—38주 분만"], answers=[3],
        concept="Quintero stage III TTTS", key="MCDA의 poly-oligo sequence, donor 방광 소실과 비정상 도플러는 Quintero stage III TTTS이다. 16–26주 stage II–IV의 표준 치료는 태반혈관문합 태아경 레이저다.",
        steps=["공유 태반 MCDA인지 먼저 확인한다.", "양수 불균형과 donor bladder 소실로 TTTS를 진단한다.", "제대동맥 REDV가 있어 stage III로 올리고 레이저 가능한 태아치료센터로 의뢰한다."],
        choice_explanations=["stage I은 donor 방광이 보이고 도플러 이상이 없어야 한다.", "방광 소실만이면 stage II지만 현재 도플러 이상도 있다.", "정답. stage III이며 23주는 레이저 표준치료 주수다.", "TAPS는 주로 MCA-PSV 불일치로 진단하며 큰 양수 불균형이 핵심이 아니다.", "단일아 FGR처럼 38주까지 기다리는 것은 TTTS의 급성 위험을 무시한다."],
        criteria=["TTTS stage I: poly-oligo, donor 방광 보임", "Stage II: donor 방광 안 보임", "Stage III: UA/DV/UV의 중증 도플러 이상", "Stage IV: 수종; Stage V: 한 태아 이상 사망"],
        review="MCDA는 16주부터 적어도 2주 간격으로 양수와 방광을 감시한다. TTTS와 TAPS, 선택적 FGR은 진단 단서와 치료가 다르다.", source_keys=["ttts"]),
    predicted("08", 2,
        stem="임신 25주 단태아의 EFW가 2백분위수이다. 양수와 제대동맥 도플러는 정상이고 구조기형은 보이지 않는다. 가장 적절한 초기 평가를 모두 고르면?",
        choices=["정밀 구조초음파", "양수천자와 염색체 microarray를 제안", "위험요인 없이 TORCH IgM 패널 전체를 일률 시행", "제대동맥 도플러 추적", "실데나필 투여"], answers=[1,2,4],
        concept="32주 미만 조기 FGR 평가", key="25주 severe early-onset FGR은 태아·염색체 원인 비율이 높다. 정밀초음파, 진단검사/CMA 제안과 제대동맥 도플러 감시가 핵심이다.",
        steps=["EFW <3백분위로 severe FGR, 진단시기 <32주로 early FGR을 확인한다.", "구조평가와 유전 진단 선택권을 제공한다.", "불필요한 감염 패널·효과 없는 치료 대신 도플러로 태반 악화를 추적한다."],
        choice_explanations=["정답. 조기 FGR은 동반기형을 놓치지 않도록 상세 해부학 평가가 필요하다.", "정답. 설명되지 않는 32주 미만 FGR에서도 CMA 포함 진단검사를 제안한다.", "위험요인이 없으면 toxoplasma·rubella·herpes 일률검사를 권하지 않는다; 양수천자를 한다면 CMV PCR을 고려한다.", "정답. 제대동맥 도플러는 악화와 분만시기 결정에 임상효용이 있다.", "실데나필은 태내 FGR 치료로 권고되지 않는다."],
        criteria=["FGR: EFW 또는 AC <10백분위", "Severe: EFW <3백분위", "Early-onset: 32주 미만 진단"],
        review="SGA는 작게 태어난 신생아의 통계적 표현이고 FGR은 태아 성장 잠재력 미달을 뜻한다. 실제 문제에서는 백분위, 성장속도, 도플러와 원인을 함께 본다.", source_keys=["fgr"]),
    predicted("08", 3,
        stem="임신 31주 severe FGR 태아의 제대동맥에서 REDV가 확인되었다. 스테로이드 1회차 투여 뒤 CTG에서 반복 prolonged deceleration이 나타난다. 다음 처치는?",
        choices=["스테로이드 48시간 완료까지 반드시 기다린다", "즉시 분만을 준비하고 32주 미만 MgSO₄ 신경보호를 투여한다", "37주까지 외래 감시", "양수주입술", "모체 고단백 식이만 처방"], answers=[2],
        concept="FGR 감시 악화와 즉시 분만", key="REDV에 반복 prolonged deceleration까지 생기면 태아상태가 악화된 것이다. 스테로이드 완료를 위해 위험한 분만을 늦추지 않고 즉시 분만하며 MgSO₄를 고려한다.",
        steps=["REDV 자체가 30–32주 분만 범주임을 확인한다.", "CTG prolonged deceleration을 추가 비안심 소견으로 본다.", "태아 소생과 수술 준비를 하며 신경보호·신생아팀을 병행한다."],
        choice_explanations=["모체·태아 적응증이 생기면 스테로이드 완료를 위해 분만을 지연하지 않는다.", "정답. 즉시 분만과 함께 32주 미만 신경보호를 준비한다.", "REDV와 비안심 CTG는 외래·만삭 대기 대상이 아니다.", "태반혈관 저항과 반복 감속을 양수주입으로 해결할 수 없다.", "영양만으로 급성 태반기능부전을 교정하지 못한다."],
        criteria=["REDV 권고 분만: 30–32주", "태아감시 악화·반복 감속은 권고 주수보다도 즉시 분만을 앞당길 수 있음", "<32주 분만 임박: MgSO₄ 신경보호"],
        review="분만주수 표는 안정된 환자의 기본 창이다. CTG, BPP, 모체질환이 악화되면 숫자표보다 현재 안전이 우선한다.", source_keys=["fgr"]),

    predicted("09", 1,
        stem="양막파수 후 제왕절개한 산모가 수술 4일째 38.8℃ 발열, 자궁압통, 악취 나는 오로를 보인다. 혈액배양 전 상태는 안정적이고 약물 알레르기는 없다. 경험적 항생제는?",
        choices=["경구 metronidazole 단독", "정맥 clindamycin + gentamicin", "vancomycin 단독", "azithromycin 1회", "항생제 없이 자궁마사지"], answers=[2],
        concept="산후 자궁내막염", key="제왕절개·장시간 막파수 뒤 산후 발열, 자궁압통과 악취 오로는 다균성 산후 자궁내막염이다. 광범위 혐기성·그람음성균을 덮는 IV clindamycin+gentamicin이 고전적 1차 요법이다.",
        steps=["산후 발열의 시점과 제왕절개·막파수 위험요인을 확인한다.", "자궁압통·악취 오로로 상처감염·요로감염보다 자궁내막염을 우선한다.", "정맥 광범위 치료를 시작하고 48–72시간 반응이 없으면 농양·골반혈전정맥염·enterococcus를 재평가한다."],
        choice_explanations=["단독 metronidazole은 호기성 그람음성균 등을 충분히 덮지 못한다.", "정답. 산후 자궁내막염의 표준 경험적 조합이다.", "vancomycin 단독은 다균성 골반감염의 그람음성·혐기성 범위를 놓친다.", "1회 macrolide로 확립된 자궁내막염을 치료할 수 없다.", "감염은 자궁무력 산후출혈과 달라 항생제가 필요하다."],
        criteria=["산후 자궁내막염은 임상진단: 산후 발열 + 자궁 압통/악취 오로, 다른 감염원 배제", "위험요인: 제왕절개, 장시간 진통·막파수, 다수 내진"],
        review="치료 후 열이 지속되면 단순히 같은 항생제를 반복하지 않는다. enterococcus를 위한 ampicillin 추가, 잔류 태반·농양 영상, septic pelvic thrombophlebitis를 단계적으로 검토한다.", source_keys=[]),
    predicted("09", 2,
        stem="분만 2주째 완전모유수유 중인 여자가 피임을 원한다. 모유량 감소와 산후 혈전 위험 때문에 가장 피해야 할 방법은?",
        choices=["프로게스틴 단일 피임약", "etonogestrel 피하 임플란트", "구리 자궁내장치", "에스트로겐-프로게스틴 복합피임약", "medroxyprogesterone 주사"], answers=[4],
        concept="수유 중 산후 피임", key="산후 2주는 VTE 위험이 높고 수유가 확립되지 않은 시기다. 에스트로겐 함유 복합피임은 혈전 위험을 더하고 모유량에 영향을 줄 수 있어 피한다.",
        steps=["산후 경과 2주와 모유수유 여부를 확인한다.", "에스트로겐 함유 여부로 선택지를 나눈다.", "프로게스틴 단독·IUD 등 대안을 환자 선호와 금기에 맞춰 선택한다."],
        choice_explanations=["프로게스틴 단독약은 산후 사용 가능한 대안이다.", "임플란트는 효과적인 산후 LARC 선택지다.", "구리 IUD는 에스트로겐이 없고 수유량을 줄이지 않는다.", "정답. 초기 산후 VTE와 수유 문제 때문에 부적절하다.", "DMPA도 프로게스틴 단독으로 사용할 수 있으나 개인 위험·선호를 상담한다."],
        criteria=["복합호르몬피임: 산후 초기 VTE 위험 때문에 금기/비권고", "수유 중에는 최소 4–6주, 수유 확립 전 에스트로겐을 피하는 것이 일반적", "프로게스틴 단독·IUD·임플란트는 산후 사용 가능"],
        review="산후 피임은 ‘수유 여부’만이 아니라 출산 후 경과일, VTE 위험인자, 감염·출혈, 향후 임신계획과 방법별 지속기간을 함께 본다.", source_keys=["postpartum_bc"]),
    predicted("09", 3,
        stem="분만 3주째 모유수유 중인 산모가 한쪽 유방의 국소 발적과 통증, 38.3℃ 발열을 호소한다. 뚜렷한 파동성 종괴는 없다. 가장 적절한 처치는?",
        choices=["모유수유를 즉시 영구 중단한다", "효과적인 유방 비우기·진통소염과 항포도알균 항생제를 시행한다", "유방절제술", "에스트로겐을 투여한다", "치료 없이 2주 기다린다"], answers=[2],
        concept="수유기 유방염", key="국소 염증과 전신 증상은 lactational mastitis에 맞는다. 수유/유축을 지속해 배액하고 지지요법과 항포도알균 항생제를 사용한다.",
        steps=["울혈만인지 전신증상을 동반한 감염성 유방염인지 구분한다.", "파동성 종괴가 없어 당장 농양 절개보다 유방염 치료를 시작한다.", "48시간 내 호전이 없거나 종괴가 생기면 초음파·배양으로 농양/MRSA를 평가한다."],
        choice_explanations=["대부분 수유 지속이 안전하고 배액에 도움이 된다.", "정답. 수유 유지, 냉찜질·NSAID와 적절한 항생제가 기본이다.", "농양도 우선 배액이며 유방절제는 과도하다.", "에스트로겐은 치료가 아니며 수유량을 줄일 수 있다.", "발열과 국소 염증을 방치하면 농양으로 진행할 수 있다."],
        criteria=["유방염: 국소 유방 염증 소견 ± 발열·오한·근육통", "농양 의심: 지속 발열, 치료 불응, 파동성/지속 종괴 → 초음파와 배액"],
        review="‘막힌 젖관-염증성 유방염-세균성 유방염-농양’은 연속선이다. 과도한 마사지로 조직손상을 만들지 말고, 배액과 항생제·영상의 시점을 구분한다.", source_keys=["breastfeeding"]),

    predicted("10", 1,
        stem="임신 8주로 추정되는 여자의 질초음파에서 자궁내 배아 CRL이 7.4 mm인데 심장박동이 없다. 자궁목은 닫혀 있고 활력징후는 안정적이다. 진단은?",
        choices=["생존 가능한 초기 자궁내임신", "확정된 초기임신소실(계류유산)", "불가피유산", "불완전유산", "자궁외임신"], answers=[2],
        concept="초음파 초기임신소실 확진", key="CRL ≥7 mm인 배아에서 심장박동이 없으면 임신 실패 확진 기준을 충족한다. 닫힌 자궁목과 잔류 자궁내 임신조직은 계류유산 양상이다.",
        steps=["자궁내 배아가 확인되어 PUL·자궁외임신과 구분한다.", "CRL 7.4 mm가 확진 경계값을 넘고 심박동이 없음을 확인한다.", "안정 환자에게 기대·약물·흡인수술의 장단점을 설명한다."],
        choice_explanations=["CRL 경계값을 넘었는데 심박동이 없어 생존 가능으로 볼 수 없다.", "정답. 초음파 확진 기준을 충족한 missed early pregnancy loss다.", "불가피유산은 보통 자궁목 개대와 진행성 출혈/통증이 있다.", "불완전유산은 일부 임신조직이 배출된 상태다.", "자궁내 배아가 직접 확인되어 자궁외임신이 아니다."],
        criteria=["확진: CRL ≥7 mm인데 심박동 없음", "확진: MSD ≥25 mm인데 배아 없음", "경계 미만이면 원하는 임신을 손상시키지 않도록 7–10일 후 반복 초음파"],
        review="단일 hCG나 애매한 작은 CRL로 임신소실을 서둘러 확진하지 않는다. 확진 뒤 안정 환자는 기대요법, mifepristone+misoprostol, 흡인수술 중 선호에 따라 선택할 수 있다.", source_keys=["epl"]),
    predicted("10", 2,
        stem="임신 6주 추정, 활력징후가 안정된 여자의 질초음파에서 자궁내 임신낭과 자궁부속기 종괴가 모두 보이지 않는다. β-hCG는 2,100에서 48시간 뒤 3,000 mIU/mL로 증가했다. 가장 적절한 다음 단계는?",
        choices=["정상임신으로 확정하고 추적 종료", "자궁외임신으로 확정해 즉시 methotrexate", "pregnancy of unknown location으로 연속 β-hCG와 반복 질초음파", "즉시 복강경", "프로게스테론만 투여"], answers=[3],
        concept="Pregnancy of unknown location", key="hCG 양성이지만 초음파로 임신 위치가 확인되지 않아 PUL이다. 원하는 생존 임신과 자궁외임신 가능성이 모두 남으므로 안정 환자에서는 연속 hCG·초음파로 위치를 확정한다.",
        steps=["초음파에서 자궁내·자궁외 임신이 모두 확인되지 않았음을 PUL로 정의한다.", "48시간 hCG 상승만으로 위치나 생존성을 확정할 수 없음을 확인한다.", "파열 경고증상을 교육하고 hCG 추세와 반복 TVUS로 추적한다."],
        choice_explanations=["정상 위치 임신이 아직 확인되지 않았다.", "단일 추세와 임의 discriminatory zone만으로 MTX를 주면 생존 IUP를 손상시킬 수 있다.", "정답. 안정 PUL의 핵심은 위치가 밝혀질 때까지 안전한 연속 추적이다.", "혈역학 불안정·복막자극·명확한 파열 단서가 없어 즉시 수술 근거가 없다.", "프로게스테론은 임신 위치를 진단하지 못하며 파열 위험 감시를 대체하지 않는다."],
        criteria=["PUL: 임신반응 양성이나 TVUS에서 자궁내·자궁외 임신이 보이지 않음", "hCG 변화는 보조자료이며 단일 수치/discriminatory level만으로 MTX 결정 금지", "불안정·복막자극·파열 의심은 즉시 수술 평가"],
        review="PUL은 최종 진단이 아니라 추적 상태다. 정상 IUP, 실패 IUP, 자궁외임신 중 하나로 귀결될 때까지 hCG·초음파와 증상을 함께 추적한다.", source_keys=["epl", "ectopic"]),
    predicted("10", 3,
        stem="임신 8주인 여자가 갑작스러운 편측 복통과 어지럼증으로 왔다. 혈압 86/52 mmHg, 맥박 126회/분이고 질초음파에서 자궁내 임신낭은 없으며 난관 종괴와 많은 복강내 액체가 보인다. 처치는?",
        choices=["48시간 뒤 hCG 검사", "methotrexate 단회요법", "응급 수술과 출혈 소생", "1주 뒤 초음파", "misoprostol 경구투여"], answers=[3],
        concept="파열 자궁외임신", key="쇼크, 난관 종괴와 많은 복강내 액체는 파열 자궁외임신에 의한 복강내출혈이다. hCG 추적이나 MTX가 아니라 혈액 소생과 응급 수술이 필요하다.",
        steps=["저혈압·빈맥을 출혈성 쇼크로 인식한다.", "빈 자궁, 난관 종괴, hemoperitoneum을 파열 자궁외임신으로 연결한다.", "대구경 정맥로·혈액제제와 동시에 수술팀을 가동한다."],
        choice_explanations=["추적검사를 기다릴 상태가 아니다.", "MTX는 안정적이고 파열되지 않은 선별 환자에서만 고려한다.", "정답. 생명을 위협하는 출혈을 수술로 조절하고 소생한다.", "일주일 지연하면 치명적 출혈이 진행한다.", "misoprostol은 자궁내 임신소실 관리 약제로 난관 파열을 치료하지 못한다."],
        criteria=["파열 의심: 혈역학 불안정, 복막자극, 상당한 복강내 액체/출혈", "수술 우선: 불안정, 파열, MTX 금기·실패, 확실한 추적 불가 등"],
        review="자궁외임신 치료는 ‘hCG가 몇이면 MTX’ 한 줄이 아니다. 안정성, 파열, 태아심박동, 종괴 크기, hCG, 간·신장·혈액상태와 추적 가능성을 종합한다.", source_keys=["ectopic"]),
]


def main() -> None:
    payload = json.loads(DATA.read_text(encoding="utf-8"))
    ids = {question["id"] for question in PREDICTED}
    payload["questions"] = [question for question in payload["questions"] if question.get("id") not in ids]
    payload["questions"].extend(PREDICTED)
    payload["questions"].sort(key=lambda item: (item["lectureNumber"], -int(item["year"]), item.get("number", 0), item["id"]))
    DATA.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"PREDICTED_2026_APPLIED count={len(PREDICTED)} total={len(payload['questions'])}")


if __name__ == "__main__":
    main()
